### ISSUE TITLE
v2.0.0: every tool call fails with "keyValidator._parse is not a function" (zod 4.x incompatible with MCP SDK)

### ISSUE THREAD

**Issue by makemachineco** [suekou/mcp-notion-server#82]
## Summary

v2.0.0 is non-functional as an MCP server in Claude Desktop: every tool call fails with `keyValidator._parse is not a function` before the request reaches the Notion API. v1.2.4 works correctly in the identical environment and config.

## Environment

- `@suekou/mcp-notion-server` 2.0.0 (via `npx -y @suekou/mcp-notion-server`)
- Host: Claude Desktop (macOS), stdio transport
- Auth: internal integration token, content access granted and verified (the same token works on v1.2.4)

## Reproduction

1. Configure the server per the README quick start (npx, latest = 2.0.0).
2. Call any tool — e.g. `notion_search` with `{"query": "test"}`, or `notion_query_data_source` with a valid `data_source_id`.
3. Every call returns:

```
keyValidator._parse is not a function
```

This affects all tools, including read-only ones. We have also observed tool input schemas being published with empty `properties` objects, so MCP clients can't see parameter definitions either.

## Suspected root cause

v2.0.0's package.json depends on `"zod": "^4.4.1"` alongside `@modelcontextprotocol/sdk ^1.11.2`. The MCP SDK's schema handling (zod-to-json-schema) is incompatible with zod 4.x — this exact failure mode is documented upstream:

- modelcontextprotocol/typescript-sdk#906 (zod 4 incompatibility)
- The same break hit other servers, e.g. modelcontextprotocol/servers#3083

v1.2.4 has no zod 4 dependency and works correctly, which is consistent with this diagnosis.

## Suggested fix

Pin zod to `^3.25.x` (the version line the MCP SDK supports), or upgrade to an SDK version with zod 4 support, and verify tool calls against a real MCP host before release.

## Workaround for other users

Pin the previous release in your MCP host config:

```json
"args": ["-y", "@suekou/mcp-notion-server@1.2.4"]
```

Thanks for the server — v1.x has been solid for over a year of daily use.

**Comment by suekou** [comment]
@makemachineco 
Thanks for the detailed report. This was really helpful.

I tracked this down to the MCP SDK version range in v2.0.0. The package could resolve to an older SDK version that does not handle Zod v4 schemas correctly, which matches the empty `properties` schemas and `keyValidator._parse is not a function` failure you saw.

I’ve pinned the SDK to a Zod v4-compatible version in #86 and published the fix as `v2.0.1`.

Could you try `@suekou/mcp-notion-server@2.0.1` when you have a chance?
